#!/usr/bin/env python3
import argparse
import re
import numpy as np
import multiprocessing as mp
from time import time, sleep
from typing import List, Dict, Set, Tuple
from functools import partial
from copy import copy

parser = argparse.ArgumentParser()
parser.add_argument("-q", "--quordle", action='store_true',
                    help="Whether to use the default settings for Quordle")
parser.add_argument("-l", "--length", type=int,
                    help="Number of letters in each word")
parser.add_argument("-c", "--count", type=int,
                    help="Number of words to be solved")
parser.add_argument("-g", "--guesses", type=int,
                    help="Number of letters in each word")
args = parser.parse_args()
WORD_LEN      = args.length if args.length else 5
WORD_COUNT    = args.count if args.count else (4 if args.quordle else 1)
TOTAL_GUESSES = args.guesses if args.guesses else (9 if args.quordle else 6)
ALPHABET = set('abcdefghijklmnopqrstuvwxyz')

# TODO: add ability to use known filtered-out words as guesses if they have a better chance of
#       narrowing down the remaining words.

# TODO: When there are few options left for one word, pick a word that will narrow it down.
#       Had 2 problems in quordle that had "dread", "dream", "clock", and "chock" as options.
#       a single word guess that included an "m", "l", and "h" would have solved both at once.

# TODO: Let the user choose a different word to use as their guess.


class Problem:
	"""The current state of one of the words to be solved.

	number: `int`: Every letter that isn't in the word.
	unusedLetters `set`(`str`): Every letter that isn't in the word.
	letterCounts `dict`{`str` `int`}: A dict of the minimum number of times
		each letter appears in the word.
	positions `list`[`set`(`str`)]: For each position, there's a set of every
		letter that might be in that position. Set contains only one letter if
		the position has been solved.
	possibleWords `list`[`str`]: Every word that hasn't been ruled out.

	lastGuessResult `str`: Provided by the user; denotes the correctness of
		each letter in the last guess.
			0: letter is not in word
			1: letter exists in different position (yellow)
			2: letter is in correct position (green)
	"""
	number: int
	unusedLetters: Set[str]
	letterCounts: Dict[str, int]
	positions: List[Set[str]]
	possibleWords: List[str]
	positionSums: Dict[str, List[int]]
	guesses: List[str]
	lastGuessResult: str
	def __init__(self, number: int, words: List[str]):
		self.number = number
		self.unusedLetters = set()
		self.letterCounts = {l: 0 for l in ALPHABET}
		self.positions = [copy(ALPHABET) for _ in range(WORD_LEN)]
		self.possibleWords = copy(words)
		self.positionSums = dict()
		self.guesses = []
		self.lastGuessResult = '0' * WORD_LEN

	def getUserResponse(self) -> str:
		while True:
			response = input("Input the result for word #{}:  ".format(self.number))
			if set(response).difference("012"):
				print("\nPlease be sure to input the result as a {} digit ".format(WORD_LEN) +
				      "number consisting only of the following values:\n" +
				      "  0 - (Gray)   The letter isn't in the word.\n" +
				      "  1 - (Yellow) The letter is in a different position.\n" +
				      "  2 - (Green)  The letter is in the correct position.\n")
			elif len(response) != WORD_LEN:
				print("Please be sure that the number of digits matches the length of the word.")
			else:
				self.lastGuessResult = response
				return response

	def isValidWord(self, word: str) -> str:
		def containsLetters(word: str) -> bool:
			return all(word.count(letter) >= count for letter, count in self.letterCounts.items())
		def positionsMatch(word: str) -> bool:
			return all(word[i] in letters for i, letters in enumerate(self.positions))
		return (containsLetters(word) and positionsMatch(word) and word not in self.guesses)
	def updateFromResult(self) -> bool:
		"""Rules out words that couldn't be possible based on the last guess result.
		`self.possibleWords` is then updated accordingly.

		Returns:
			bool: Whether or not this problem has been solved. Either because the
				user responded with "22222" or because there is only one possible
				word left.
		"""
		if self.lastGuessResult == "2" * WORD_LEN:
			self.possibleWords = [self.guesses[-1]]
			return True
		newLetterCounts = {}
		for i in re.finditer('2', self.lastGuessResult):
			self.positions[i.start()] = set([self.guesses[-1][i.start()]])
			if self.guesses[-1][i.start()] in newLetterCounts.keys():
				newLetterCounts[self.guesses[-1][i.start()]] += 1
			else:
				newLetterCounts[self.guesses[-1][i.start()]] = 1
		for i in re.finditer('1', self.lastGuessResult):
			self.positions[i.start()].difference_update(self.guesses[-1][i.start()])
			if self.guesses[-1][i.start()] in newLetterCounts.keys():
				newLetterCounts[self.guesses[-1][i.start()]] += 1
			else:
				newLetterCounts[self.guesses[-1][i.start()]] = 1
		for i in re.finditer('0', self.lastGuessResult):
			if not self.guesses[-1][i.start()] in newLetterCounts.keys():
				self.unusedLetters.add(self.guesses[-1][i.start()])

		for position in self.positions:
			position.difference_update(self.unusedLetters)

		for key, count in newLetterCounts.items():
			self.letterCounts[key] = max(count, self.letterCounts.get(key, 0))
		# Weed out words that aren't valid.
		self.possibleWords = [word for word in self.possibleWords if self.isValidWord(word)]
		if len(self.possibleWords) == 1:
			return True
		return False

	def getMatchedLetters(self, letter: str, word: str) -> List[bool]:
		return [letter == l for i, l in enumerate(word) if self.positions[i] != set(l)]
	def calcBasicScores(self) -> Dict[str, List[int]]:
		for letter in self.positionSums.keys():
			start = time()
			with mp.Pool(mp.cpu_count()) as pool:
				func = partial(self.getMatchedLetters, letter)
				letterMap = np.array(pool.map(func, self.possibleWords))
			print("getMatchedLetters done in " + str(time() - start))
			self.positionSums[letter] = np.sum(letterMap, axis=0)
			if sum(self.positionSums[letter]) == 0:
				self.positionSums.pop(letter)
				self.unusedLetters.add(letter)

		# {"a": [10, 0, 0, 3, 11],  "b": [10, 0, 0, 3, 11],  ...}
		return self.positionSums

	def getWordScore(self, word: str) -> Tuple[str, int]:
		# TODO: maybe substitute sum for an algorithm that prefers all positions to have high
		# score instead of totals?
		default = [0] * WORD_LEN
		letterScores = []
		repeatLetterMod = 0
		for i, l in enumerate(word):
			# reapeatLetterMod is used to skew the algorithm away from choosing words that have
			# letters in the same position as previous guesses. So "stars" should have a
			# slightly lower score if "sorry" has already been guessed.
			repeatLetterMod += any(l == guess[i] for guess in self.guesses)
			dupeLetterMod = word.count(l)
			letterScores += [(self.positionSums.get(l, default)[i] /
			                  (word.count(l) * (1 + repeatLetterMod ** 2) * dupeLetterMod))]
		return word, sum(letterScores)
	def calcWordScores(self) -> Tuple[Dict[str, List[int]],  Set[str]]:
		self.calcBasicScores()
		with mp.Pool(mp.cpu_count()) as pool:
			wordScores = pool.map(self.getWordScore, self.possibleWords)
		wordScores.sort(key=lambda x: x[1], reverse=True)
		wordScores = wordScores[:100]   # TODO: Maybe adjust Trim value
		return set(pair[0] for pair in wordScores)


def getWordList() -> List[str]:
	# TODO: "iliad" was not in this list of words. What other words aren't included?
	def noSymbols(word: str) -> bool:
		return len(set(word.lower()).difference(ALPHABET)) == 0
	def isValidWord(word: str) -> bool:
		return (len(word) == WORD_LEN) and noSymbols(word) and (not word.isupper())
	def gerWordsFromFile(fileName: str) -> Set[str]:
		with open(fileName, 'r') as f:
			lines = [line[:-1].strip().split(", ") for line in f.readlines()]
		return set([word[:-1] if word.endswith("%") else word
		            for line in lines
		            for word in line])
	neolSet = gerWordsFromFile("12dicts-6.0.2/Special/neol2016.txt")
	mainSet = gerWordsFromFile("12dicts-6.0.2/American/2of12inf.txt")
	expandedSet = gerWordsFromFile("12dicts-6.0.2/Lemmatized/2+2+3lem.txt")
	print(len(neolSet.difference(expandedSet)))
	print(len(mainSet.difference(expandedSet)))
	words = [word.lower() for word in list(mainSet.union(neolSet, expandedSet))
	         if isValidWord(word)]
	print(len(words))
	return words



# wordScores = (word, sum())
# wordScores = [wordScore for wordScore in wordScores
#               if sum(wordScore[1]) > 1].sort(key=lambda x: x[1])
# TODO: Modify this to solve for problems like: ['taunt', 'daunt', 'jaunt', 'gaunt', 'vaunt']
# def getContextualScores(problems: List[Problem]) -> List[Tuple[str, float]]:
# 	if all(len(problem.possibleWords) < 8 for problem in problems):
# 		decidingLetters = []
# 		commonLetters = []
# 		for problem in problems:
# 			for position in problem.positions
# 			for letter in problem.positionSums.keys():
# 				if sum(problem.positionSums[letter]) == 1
# 				set().symmetric_difference()
# 		return
# 	# TODO: score normally


if __name__ == "__main__":
	manager = mp.Manager()
	mp.set_start_method('spawn', True)
	words = getWordList()
	# print("using" in words)
	problems = [Problem(i + 1, words) for i in range(WORD_COUNT)]
	unspokenSolves = []
	guess = "coney"
	for guessIndex in range(TOTAL_GUESSES):
		print(guess)

		for problem in problems:
			problem.getUserResponse()

		solvedProblems = []
		allWordScores = []
		for problem in problems:
			problem.guesses += [guess]
			if problem.updateFromResult():
				solvedProblems += [problem]
				if problem.guesses[-1] != problem.possibleWords[0]:
					unspokenSolves += [problem.possibleWords[0]]
				continue  # Word solved! wordState to be removed from list.

			allWordScores += [problem.calcWordScores()]
			# allBasicScores += [problem.positionSums]
			print(problem.possibleWords)

		if solvedProblems:
			[problems.remove(solvedProblem) for solvedProblem in solvedProblems]
			if not problems:
				break  # All problems solved!

		if unspokenSolves:
			guess = unspokenSolves.pop()
		else:
			topWords = set().union(*allWordScores)
			scores = []
			for word in topWords:
				score = sum(problem.getWordScore(word)[1] for problem in problems)
				scores += [(word, score)]
			scores.sort(key=lambda x: x[1], reverse=True)
			guess = scores[0][0]


	for solution in unspokenSolves:
		print(solution)
